### ISSUE TITLE
Funtzionatzeari utzi dio

### ISSUE THREAD

**Issue by ddceca** [erral/plugin.video.eitb#10]
Joan den astean pluginak funtzionatzeari utzi zion. Hau esaten du logak:

****

2024-04-29 18:01:07.482 T:7929    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'simplejson.errors.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/home/dce/.kodi/addons/plugin.video.eitb/addon.py", line 84, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/dce/.kodi/addons/plugin.video.eitb/addon.py", line 44, in router
                                                       vh.list_programs()
                                                     File "/home/dce/.kodi/addons/plugin.video.eitb/video.py", line 51, in list_programs
                                                       programs = get_programs()
                                                                  ^^^^^^^^^^^^^^
                                                     File "/home/dce/.kodi/addons/plugin.video.eitb/utils.py", line 25, in get_programs
                                                       return data.json().get("member")
                                                              ^^^^^^^^^^^
                                                     File "/home/dce/.kodi/addons/script.module.requests/lib/requests/models.py", line 971, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib64/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
                                                       return _default_decoder.decode(s)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib64/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
                                                       obj, end = self.raw_decode(s)
                                                                  ^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib64/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
                                                       return self.scan_once(s, idx=_w(s, idx).end())
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2024-04-29 18:01:07.528 T:7928    error <general>: GetDirectory - Error getting plugin://plugin.video.eitb/?action=videomenu&option=all_tvshows
2024-04-29 18:01:07.533 T:7807    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.eitb/?action=videomenu&option=all_tvshows) failed
2024-04-29 18:01:07.719 T:7931  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
****

Eskerrik asko aldez aurretik!

**Comment by erral** [comment]
Eskerrik asko abisuagatik. EITBren webguneko deiak aldatu egin dira eta eguneratu egin behar ditugu.
